Make counter-type regulators work
lrascao/raterl pull request #9
Opened 2020-01-22 13:52 UTC by g-andrade

Move the accounting of slots to the associated `raterl_queue` processes and monitor slot owners in order to ensure that even brutally killed processes free up any slots they might have been using.

(Keep using ETS for rate-type regulators, however.)

Closes #8 .

2020-01-22 14:01 UTC, g-andrade commented
I've taken the liberty of removing the Travis target for OTP 17, since not even `rebar3` can run on it nowadays.

2020-01-25 13:50 UTC, lrascao requested changes

2020-01-25 13:50 UTC, lrascao commented on src/raterl_utils.erl
> +-ifdef(NO_MAPS_TAKE).
this is no longer since 17 support got dropped right?

2020-01-25 13:53 UTC, g-andrade commented
OTP 18 requires it, unfortunately.

On Sat, Jan 25, 2020, 13:50 Luis Rascão <notifications@github.com> wrote:

> *@lrascao* requested changes on this pull request.
> ------------------------------
>
> In src/raterl_utils.erl
> <https://github.com/lrascao/raterl/pull/9#discussion_r370934472>:
>
> > @@ -39,6 +40,21 @@ queue_name(Name) ->
>      list_to_atom("raterl_" ++
>                   atom_to_list(Name)).
>
> +-ifdef(NO_MAPS_TAKE).
>
> this is no longer since 17 support got dropped right?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lrascao/raterl/pull/9?email_source=notifications&email_token=ABYCJ7WBWKFM6HRDGE3GBADQ7Q7R5A5CNFSM4KKGEFR2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCTBQWWY#pullrequestreview-348326747>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABYCJ7WF6DMUTTPI6XQCYE3Q7Q7R5ANCNFSM4KKGEFRQ>
> .
>

2020-01-25 14:03 UTC, lrascao commented
right

> OTP 18 requires it, unfortunately.
> […](#)
> On Sat, Jan 25, 2020, 13:50 Luis Rascão ***@***.***> wrote: ***@***.**** requested changes on this pull request. ------------------------------ In src/raterl_utils.erl <[#9 (comment)](https://github.com/lrascao/raterl/pull/9#discussion_r370934472)>: > @@ -39,6 +40,21 @@ queue_name(Name) -> list_to_atom("raterl_" ++ atom_to_list(Name)). +-ifdef(NO_MAPS_TAKE). this is no longer since 17 support got dropped right? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub <#9?email_source=notifications&email_token=ABYCJ7WBWKFM6HRDGE3GBADQ7Q7R5A5CNFSM4KKGEFR2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCTBQWWY#pullrequestreview-348326747>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABYCJ7WF6DMUTTPI6XQCYE3Q7Q7R5ANCNFSM4KKGEFRQ> .

2020-01-25 14:03 UTC, merged